spring.application.name=itemsStorage

# SQLite ? ???? ????? ?????? items.db ????? ? ???????????
#spring.datasource.url=jdbc:sqlite:items.db
#spring.datasource.driver-class-name=org.sqlite.JDBC

# Hibernate ??? ??????? ??????? ??? ???????
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

#spring.datasource.url=jdbc:${DATABASE_URL}
#spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ????
server.port=8080
skill.id=${SKILL_ID:}